pipeline {
    agent {
        label 'admin'
    }
    stages {
        stage('SCM') {
            steps {
                sh 'git clone https://github.com/RatiRanjanDas/javaprojrepo.git'
            }
        }
        stage('Build') {
            steps {
                dir('javaprojrepo/hellospringeks') {
		            sh 'mvn clean install'
		            }
            }
        }
        stage('docker build') {
            steps {
	              dir('javaprojrepo/hellospringeks') {
                sh 'docker build -t ratidas/hellospringeks .'
		            }
            }
        }
        stage('docker login') {
            steps {
		        withCredentials([string(credentialsId: 'docker', variable: 'dockerpwd')]) {
		        sh 'docker login -u ratidas -p ${dockerpwd}'
		        }
		        sh 'docker push ratidas/hellospringeks'
		        }
	      }
    }
}
